/* Keep this list alphabetized */

export const RECIPE_FETCH = 'RECIPE_FETCH';
export const RECIPE_FETCH_FAILURE = 'RECIPE_FETCH_FAILURE';
export const RECIPE_FETCH_SUCCESS = 'RECIPE_FETCH_SUCCESS';
export const RECIPE_RECIEVE = 'RECIPE_RECIEVE';
export const RECIPES_FETCH = 'RECIPES_FETCH';
export const RECIPES_FETCH_FAILURE = 'RECIPES_FETCH_FAILURE';
export const RECIPES_FETCH_SUCCESS = 'RECIPES_FETCH_SUCCESS';
export const REVISION_FETCH = 'REVISION_FETCH';
export const REVISION_FETCH_FAILURE = 'REVISION_FETCH_FAILURE';
export const REVISION_FETCH_SUCCESS = 'REVISION_FETCH_SUCCESS';
export const REVISION_RECIEVE = 'REVISION_RECIEVE';
export const REVISIONS_FETCH = 'REVISION_FETCH';
export const REVISIONS_FETCH_FAILURE = 'REVISION_FETCH_FAILURE';
export const REVISIONS_FETCH_SUCCESS = 'REVISION_FETCH_SUCCESS';
