extends: 'normandy'
plugins:
  - mozilla

rules:
  indent: [1, 2, {SwitchCase: 1}]
  mozilla/balanced-listeners: [1]
  mozilla/no-aArgs: [1]
  mozilla/this-top-level-scope: [1]
  no-console: [1]

globals:
  require: false
  exports: true
  uneval: false
