version: 0

metadata:
  name: Normandy
  description: Normandy CI Tasks
  owner: "{{ event.head.user.email }}"
  source: "{{ event.head.repo.url }}"

tasks:
  - metadata:
      name: normandy:decision
      description: Normandy decision task
      owner: "{{ event.head.user.email }}"
      source: "{{ event.head.repo.url }}"
    provisionerId: "{{ taskcluster.docker.provisionerId }}"
    workerType: "{{ taskcluster.docker.workerType }}"
    scopes:
      - queue:create-task:aws-provisioner-v1/github-worker
      # the decision task creates tasks that run on the gecko worker for speed
      # and to ensure the same execution environment as "regular" gecko builds
      - queue:create-task:aws-provisioner-v1/gecko-1-b-linux
    payload:
      env:
      maxRunTime: 300 # 5 minutes
      image: mozilla/normandy-taskcluster:v2
      features:
        taskclusterProxy: true
      command:
        - "/bin/bash"
        - "-c"
        - >-
          git clone $GITHUB_HEAD_REPO_URL normandy &&
          pushd normandy &&
          git checkout $GITHUB_HEAD_SHA &&
          popd &&

          pushd normandy/ci/taskcluster &&
          python3.6 -m venv venv &&
          source venv/bin/activate &&
          pip install -r requirements/default.txt -c requirements/constraints.txt &&
          popd &&

          python3.6 normandy/ci/taskcluster/bin/decision.py
    extra:
      github:
        env: true
        events:
          - pull_request.opened
          - pull_request.synchronize
          - push
          - release
