actions:
  flake8:
    run: flake8 {files}
    include: "*.py"
    exclude: "docs/"
  eslint:
    run: ./node_modules/.bin/eslint {files}
    include: "*.js"
  stylelint:
    run: ./node_modules/.bin/stylelint {files}
    include:
      - "client/**/*.css"
      - "client/**/*.scss"
