/* Keep this list alphabetized */

export const ACTION_RECEIVE = 'ACTION_RECEIVE';
export const APPROVAL_REQUEST_CREATE = 'APPROVAL_REQUEST_CREATE';
export const APPROVAL_REQUEST_DELETE = 'APPROVAL_REQUEST_DELETE';
export const APPROVAL_REQUEST_RECEIVE = 'APPROVAL_REQUEST_RECEIVE';
export const EXTENSION_LISTING_COLUMNS_CHANGE = 'EXTENSION_LISTING_COLUMNS_CHANGE';
export const EXTENSION_PAGE_RECEIVE = 'EXTENSION_PAGE_RECEIVE';
export const EXTENSION_RECEIVE = 'EXTENSION_RECEIVE';
export const RECIPE_DELETE = 'RECIPE_DELETE';
export const RECIPE_LISTING_COLUMNS_CHANGE = 'RECIPES_LISTING_COLUMNS_CHANGE';
export const RECIPE_PAGE_RECEIVE = 'RECIPES_PAGE_RECEIVE';
export const RECIPE_RECEIVE = 'RECIPE_RECEIVE';
export const RECIPE_FILTERS_RECEIVE = 'RECIPE_FILTERS_RECEIVE';
export const RECIPE_HISTORY_RECEIVE = 'RECIPE_HISTORY_RECEIVE';
export const REQUEST_FAILURE = 'REQUEST_FAILURE';
export const REQUEST_SEND = 'REQUEST_SEND';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REVISION_RECEIVE = 'REVISION_RECEIVE';
export const SERVICE_INFO_RECEIVE = 'SERVICE_INFO_RECEIVE';
export const USER_RECEIVE = 'USER_RECEIVE';
