# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-13 00:53
# flake8: noqa
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('xpi', models.FileField(upload_to='extensions')),
            ],
        ),
    ]
