# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-13 01:13
# flake8: noqa
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import normandy.recipes.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20160112_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='actions',
            field=models.ManyToManyField(through='recipes.RecipeAction', to='recipes.Action'),
        ),
        migrations.AlterField(
            model_name='recipeaction',
            name='arguments',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
