# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 07:15
# flake8: noqa
from __future__ import unicode_literals

from django.db import migrations, models
import normandy.recipes.models


def action_implementation_filename(instance, filename):
    return 'actions/{instance.name}.js'.format(instance=instance)


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_recipe_locale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='implementation',
            field=models.FileField(upload_to=action_implementation_filename),
        ),
        migrations.AlterField(
            model_name='action',
            name='implementation_hash',
            field=models.CharField(editable=False, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='name',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
