# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 23:37
# flake8: noqa
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_auto_20160204_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='arguments_schema',
            new_name='arguments_schema_json',
        ),
        migrations.RenameField(
            model_name='recipeaction',
            old_name='arguments',
            new_name='arguments_json',
        ),
    ]
