# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-16 22:50
# flake8: noqa
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='revision_id',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
