# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-02 18:36
# flake8: noqa
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0025_auto_20160429_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
