# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-09 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0038_approval_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrequest',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
