# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-27 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0042_remove_invalid_signatures'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reciperevision',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='action',
            name='signature',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='action', to='recipes.Signature'
            ),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='signature',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='recipe',
                to='recipes.Signature'
            ),
        ),
    ]
