# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-06 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_squashed_0047_reciperevision_identicon_seed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='implementation',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='implementation_hash',
            field=models.CharField(editable=False, max_length=71, null=True),
        ),
    ]
