# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import normandy.recipes.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20160112_2222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeaction',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='recipeaction',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
