# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-15 19:14
# flake8: noqa
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20160113_0113'),
        ('recipes', '0003_auto_20160113_0046'),
    ]

    operations = [
    ]
