# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-09 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import normandy.recipes.validators


class Migration(migrations.Migration):

    dependencies = [("recipes", "0005_auto_20180503_2146")]

    operations = [
        migrations.AddField(
            model_name="reciperevision",
            name="filter_object_json",
            field=models.TextField(
                null=True, validators=[normandy.recipes.validators.validate_json]
            ),
        )
    ]
