# Generated by Django 2.0.5 on 2018-05-10 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("recipes", "0009_auto_20180510_2328")]

    operations = [
        migrations.AlterModelOptions(
            name="recipe", options={"ordering": ["-latest_revision__updated"]}
        ),
        migrations.RemoveField(model_name="recipe", name="enabled"),
    ]
