# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-02 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20160122_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='implementation_hash',
            field=models.CharField(editable=False, max_length=40),
        ),
    ]
