# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 20:55
# flake8: noqa
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20160202_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='arguments_schema',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
