# Generated by Django 2.0.9 on 2018-10-18 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("recipes", "0012_reciperevision_bug_number")]

    operations = [
        migrations.AlterModelOptions(name="action", options={"ordering": ("id",)}),
        migrations.AlterModelOptions(name="approvalrequest", options={"ordering": ("id",)}),
    ]
