# Generated by Django 2.0.13 on 2019-02-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("recipes", "0013_auto_20181018_2049")]

    operations = [
        migrations.AddField(
            model_name="reciperevision",
            name="experimenter_id",
            field=models.IntegerField(null=True),
        )
    ]
