# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-17 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_auto_20160204_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='implementation',
            field=models.TextField(),
        ),
    ]
