# Generated by Django 2.2.3 on 2019-08-07 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("recipes", "0014_auto_20190228_1128")]

    operations = [
        migrations.RemoveField(model_name="reciperevision", name="channels"),
        migrations.RemoveField(model_name="reciperevision", name="countries"),
        migrations.RemoveField(model_name="reciperevision", name="locales"),
    ]
