# Generated by Django 2.2.5 on 2019-09-04 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("recipes", "0015_reciperevision_extra_capabilities")]

    operations = [
        migrations.RemoveField(model_name="reciperevision", name="bug_number"),
        migrations.AddField(
            model_name="reciperevision",
            name="experimenter_slug",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
