# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-18 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_auto_20160219_0101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('order', models.IntegerField()),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='locale',
            name='order',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='country',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='locale',
        ),
        migrations.AddField(
            model_name='recipe',
            name='locales',
            field=models.ManyToManyField(blank=True, to='recipes.Locale'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='countries',
            field=models.ManyToManyField(blank=True, to='recipes.Country'),
        ),
        migrations.AlterModelOptions(
            name='locale',
            options={'ordering': ['order', 'code']},
        ),
    ]
