# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-18 19:03
from __future__ import unicode_literals

from django.db import migrations

from django_countries import countries


def add_countries(apps, schema_editor):
    Country = apps.get_model('recipes', 'Country')
    for (code, name) in countries:
        if code == 'US':
            order = 0
        else:
            order = 100

        Country.objects.update_or_create(code=code, defaults={
            'name': name,
            'order': order,
        })


def remove_countries(apps, schema_editor):
    Country = apps.get_model('recipes', 'Country')
    Country.objects.all().delete()


def set_locale_sort_order(apps, schema_editor):
    Locale = apps.get_model('recipes', 'Locale')
    english = Locale.objects.get(code='en-US')
    english.order = 0
    english.save()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_auto_20160218_2024'),
    ]

    operations = [
        migrations.RunPython(add_countries, remove_countries),
        migrations.RunPython(set_locale_sort_order, noop),
    ]
