# Generated by Django 2.2.10 on 2020-03-18 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("recipes", "0017_auto_20191008_1930")]

    operations = [
        migrations.CreateModel(
            name="WindowsVersion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nt_version", models.DecimalField(decimal_places=1, max_digits=3)),
                ("name", models.CharField(max_length=255)),
            ],
            options={"ordering": ("nt_version",)},
        )
    ]
