# Generated by Django 2.2.12 on 2021-01-28 23:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0018_windowsversion"),
    ]

    operations = [
        migrations.AddField(
            model_name="reciperevision",
            name="metadata",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
