# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-16 19:47
# flake8: noqa
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import normandy.recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_add_revision_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.Action'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='arguments_json',
            field=models.TextField(default='{}', validators=[normandy.recipes.validators.validate_json]),
        ),
        migrations.AlterField(
            model_name='country',
            name='order',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='locale',
            name='order',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='actions',
            field=models.ManyToManyField(related_name='recipes', through='recipes.RecipeAction', to='recipes.Action'),
        ),
    ]
