# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-17 00:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0021_migrate_to_single_actions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeaction',
            name='action',
        ),
        migrations.RemoveField(
            model_name='recipeaction',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='actions',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Action'),
        ),
        migrations.DeleteModel(
            name='RecipeAction',
        ),
    ]
