# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-24 23:33
# flake8: noqa
from __future__ import unicode_literals

from django.db import migrations, models


def percent_to_float(apps, schema_editor):
    """Convert from percent to float"""
    Recipe = apps.get_model('recipes', 'Recipe')
    for recipe in Recipe.objects.all():
        recipe.sample_rate /= 100
        recipe.save()


def float_to_percent(apps, schema_editor):
    """Convert from percent to float"""
    Recipe = apps.get_model('recipes', 'Recipe')
    for recipe in Recipe.objects.all():
        recipe.sample_rate *= 100
        recipe.save()


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0022_auto_20160317_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='sample_rate',
            field=models.FloatField(default=1.0, help_text='A number between 0.0 and 1.0. A value of 0.0 will select no users. A value of 1.0 will select all users')
        ),
        migrations.RunPython(percent_to_float, float_to_percent),
    ]
