# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-29 23:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0024_recipe_filter_expression'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='countries',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='locales',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='release_channels',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='sample_rate',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='start_time',
        ),
    ]
