# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-06 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0026_recipe_approver'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='signature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='signature_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
