# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-16 21:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0029_recipe_last_updated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Locale',
        ),
        migrations.DeleteModel(
            name='ReleaseChannel',
        ),
    ]
