# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-27 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0031_recipe_signing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
