# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-28 13:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import normandy.recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0033_migrate_surveys'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeRevision',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('arguments_json', models.TextField(default='{}', validators=[normandy.recipes.validators.validate_json])),
                ('filter_expression', models.TextField()),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Action')),
                ('parent', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='recipes.RecipeRevision')),
            ],
        ),
        migrations.RemoveField(
            model_name='approval',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='approvalrequest',
            name='approval',
        ),
        migrations.RemoveField(
            model_name='approvalrequest',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='approvalrequest',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='approvalrequestcomment',
            name='approval_request',
        ),
        migrations.RemoveField(
            model_name='approvalrequestcomment',
            name='creator',
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-enabled', '-latest_revision__updated']},
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='approval',
        ),
        migrations.DeleteModel(
            name='Approval',
        ),
        migrations.DeleteModel(
            name='ApprovalRequest',
        ),
        migrations.DeleteModel(
            name='ApprovalRequestComment',
        ),
        migrations.AddField(
            model_name='reciperevision',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='reciperevision',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,related_name='recipe_revisions', to=settings.AUTH_USER_MODEL)
        ),
        migrations.AddField(
            model_name='recipe',
            name='latest_revision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='latest_for_recipe', to='recipes.RecipeRevision'),
        ),
    ]
