# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-28 13:48
from __future__ import unicode_literals

import hashlib
import json

from django.db import migrations


def hash_revision_data(revision):
    data = '{}{}{}{}{}{}'.format(revision.recipe.id, revision.created, revision.name,
                                 revision.action.id, revision.arguments_json,
                                 revision.filter_expression)
    return hashlib.sha256(data.encode()).hexdigest()


def migrate_reversion_data(apps, schema_editor):
    Action = apps.get_model('recipes', 'Action')
    Recipe = apps.get_model('recipes', 'Recipe')
    RecipeRevision = apps.get_model('recipes', 'RecipeRevision')
    Version = apps.get_model('reversion', 'Version')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    ct = ContentType.objects.get(app_label='recipes', model='recipe')

    for r in Recipe.objects.all():
        revision = None

        for v in Version.objects.filter(content_type=ct, object_id=r.id).order_by(
                'revision__date_created'):

            v = Version.objects.get(revision_id=v.revision.id)

            data = json.loads(v.serialized_data)[0]['fields']

            action = Action.objects.get(id=data.get('action'))

            revision = RecipeRevision(
                recipe=r, parent=revision, created=v.revision.date_created,
                comment=v.revision.comment, user=v.revision.user, name=data.get('name'),
                action=action, arguments_json=data.get('arguments_json', ''),
                filter_expression=data.get('filter_expression', ''))

            revision.id = hash_revision_data(revision)

            revision.save()

        r.latest_revision = revision
        r.save()


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '__latest__'),
        ('reversion', '__latest__'),
        ('recipes', '0034_auto_20161128_1341'),
    ]

    operations = [
        migrations.RunPython(migrate_reversion_data),
    ]
