# Generated by Django 2.0.5 on 2018-05-10 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extension',
            options={'ordering': ('-id',)},
        ),
    ]
