# Generated by Django 2.0.9 on 2019-01-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("studies", "0002_auto_20180510_2256")]

    operations = [
        migrations.AddField(
            model_name="extension", name="hash", field=models.CharField(max_length=64, null=True)
        ),
        migrations.AddField(
            model_name="extension",
            name="version",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="extension",
            name="webext_id",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
