# Generated by Django 2.0.9 on 2019-01-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("studies", "0004_auto_20190115_0812")]

    operations = [
        migrations.AlterField(
            model_name="extension", name="hash", field=models.CharField(max_length=64)
        ),
        migrations.AlterField(
            model_name="extension", name="version", field=models.CharField(max_length=32)
        ),
        migrations.AlterField(
            model_name="extension", name="extension_id", field=models.CharField(max_length=255)
        ),
    ]
