# Generated by Django 2.0.10 on 2019-02-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("studies", "0005_auto_20190115_0812")]

    operations = [
        migrations.AddField(
            model_name="extension",
            name="hash_algorithm",
            field=models.CharField(default="sha256", max_length=16),
            preserve_default=False,
        )
    ]
