# Generated by Django 2.0.12 on 2019-03-15 00:58

from django.db import migrations, models
import normandy.studies.models


class Migration(migrations.Migration):

    dependencies = [("studies", "0006_extension_hash_algorithm")]

    operations = [
        migrations.AlterField(
            model_name="extension",
            name="xpi",
            field=models.FileField(
                unique=True, upload_to=normandy.studies.models.get_extension_filename
            ),
        )
    ]
